#!/usr/bin/env bash

# Stop when errors
set -e

# Default directories
SCRIPT_DIR="$(dirname "$0")"
cd "$SCRIPT_DIR/.."
ROOT_DIR=$(pwd)

# include test framework
. "$ROOT_DIR/script/assert.sh"

# Example
#
# assert_snapshot "my-command" "my-command.out"
assert_snapshot() {
  local test_command="$1"
  local snapshot_file;
  local snapshot_content;
  snapshot_file="$ROOT_DIR/test/__snapshots__/$2"
  if [[ "$UPDATE_SNAPSHOT" != "" || ! -f $snapshot_file ]];then
    eval "$test_command" > "$snapshot_file"
  fi
  snapshot_content=$(cat "$snapshot_file")

  assert "$test_command" "$snapshot_content"
}

# Bootstrap
cd "$ROOT_DIR/test"
. "$ROOT_DIR/test/suite.sh"
