name: Makefile

on:
  merge_group: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    - name: test
      run: make test
